name: CI/CD for CMS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t control_panel .

      - name: Push Docker Image to Registry
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker tag control_panel ${{ secrets.DOCKERHUB_USERNAME }}/control_panel:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/control_panel:latest
